export const userMicroserviceBaseUrl = 'http://localhost:8000/api/v1'
export const menuMicroserviceBaseUrl = 'http://localhost:8001/api/v1'
export const restaurantMicroserviceBaseUrl = 'http://localhost:8002/api/v1'
export const orderMicroserviceBaseUrl = 'http://localhost:8003/api/v1'
export const reviewMicroserviceBaseUrl = 'http://localhost:8004/api/v1'